import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stephen Solutions",
  description: "Generated by create next app",
   verification: {
    google: "UJecft7UmFvy4F3LkBX2pXVYzKt_SDvl78BG4jMbCxs",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="google-site-verification" content="UJecft7UmFvy4F3LkBX2pXVYzKt_SDvl78BG4jMbCxs" />
      <body
        className={`antialiased ${roboto.className} w-screen overflow-x-hidden`}
      >
        <Header />
        <main className="pt-24">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
